input {
    kafka {
    bootstrap_servers => "aladdin_kafka:9092"
    topics => ["market-trades"]
    codec => json
    client_id => "logstash_analytics"
    group_id => "analytics_group"
  }
}

filter {
  # 1. MUTATE: Data Cleaning
  # Sometimes the API might send 'quantity' as a string ("50"). 
  # We force it into an integer here so Kibana can do math on it later.
  mutate {
    convert => { "quantity" => "integer" }
  }

  # 2. DATE: Standardizing Timestamps
  # If the API sends a "trade_time" field, we map it identically to Elasticsearch's core @timestamp 
  date {
    match => [ "trade_time", "ISO8601" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "aladdin-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
